### ISSUE TITLE
No change on value change

### ISSUE THREAD

**Issue by meistroburger** [Rexshack-RedM/rsg-scoreboard#1]
Hey!

If I change the value (even in the Config) to for example 0 nothing happens to the scoreboard's crosses. Also with "TriggerServerEvent('rsg-scoreboard:server:SetActivityBusy', "wagonrobbery", true)" or "TriggerEvent('rsg-scoreboard:server:SetActivityBusy', "wagonrobbery", true)" nothing happens.

Would be great if it works <3

Thanks

**Comment by RexShack** [comment]
please join the discord : https://discord.gg/s5uSk56B65

**Comment by meistroburger** [comment]
I'm in the Discord @RexShack. Where do you want me to post such thing?

**Comment by RexShack** [comment]
please use support but can't guarantee these thing will be fixed any time soon

**Comment by RexShack** [comment]
issue fixed
